### PR TITLE
update to standard 10

### PR DESCRIPTION
**Pull request by KenanY**
This PR updates the peer dependency to `eslint-config-standard@^10.0.0`, and updates the dev dependencies accordingly. The new `eslint-plugin-*` deps are new peer deps of `eslint-config-standard`.

### CODE REVIEW

**Comment by KenanY** [comment]
Hmm, not sure why Node.js v4 failed on Travis. Seems like a dependency of `standard` wasn't installed for whatever reason. Probably should just try re-running it.

**Comment by jokeyrhyme** [comment]
I blame the `cache` setting in our .travis.yml. I think the cache has a copy of standard that depend on a React plugin for ESLint, which isn't in the cache. Or something. /shrug

Might need to discuss dropping that setting, what the benefits and downsides are...

**Comment by Flet** [comment]
Thanks for the hint @jokeyrhyme re-running with modified travis.yml now.

**Comment by Flet** [comment]
Looks like it was looking for a `eslint-plugin-react`, but it was not explicitly set as a devDep... so it was picking up a copy via the `standard` devDep. The cache probably hid this problem for a while.

I committed this to clean that up... 
https://github.com/Flet/eslint-config-semistandard/commit/b3cc9a35c79924fb7dc564e7225c9d730d0b99c2

Travis is happy now!

**Comment by Flet** [comment]
published as `eslint-config-standard@11.0.0`

**Pull request merged**
