### PR TITLE
bump deps

### LINKED ISSUE #8: Update npm peer dependencies to work with ESLint 2.0+
Hi,

I tried upgrading one of my projects to ESLint 2.0, but the upgrade failed due to peer dependency conflicts with eslint-config-semistandard

> npm ERR! peer dep missing: eslint@^1.0.0, required by eslint-config-semistandard@5.0.0
npm ERR! peer dep missing: eslint@^1.6.0, required by eslint-loader@1.2.1
npm ERR! peer dep missing: eslint-config-standard@^4.0.0, required by eslint-config-semistandard@5.0.0
npm ERR! peer dep missing: eslint-plugin-promise@^1.0.8, required by eslint-config-standard@5.1.0

Can you please update your dependencies to work with ESLint 2.0+?

Thanks!

### PR DESCRIPTION
**Pull request by jokeyrhyme**
- bump devDeps for ESLint 2.0, etc (fixes #8)

### CODE REVIEW

**Comment by natorojr** [comment]
+1 this makes a lot of sense, especially trimming down the peer deps

**Comment by jokeyrhyme** [comment]
@Flet ? any thoughts?

**Comment by Flet** [comment]
I was kinda waiting for standard v7 to release before bumping semistandard...

https://github.com/feross/standard/issues/404

**Comment by jokeyrhyme** [comment]
Ah, okay. Yeah, that makes sense.

**Comment by Flet** [comment]
I would be fine with merging this if the standard versions are kept the same for now.

Also, does it make sense to switch the standard deps to just `dependencies`?

**Comment by jokeyrhyme** [comment]
I made a separate PR: #9 

I don't believe it is necessary or beneficial to move the standard deps from devDeps to deps. That would cause every downstream project that uses eslint-config-semistandard to also download standard, for example, which is unnecessary.

**Comment by jokeyrhyme** [comment]
I notice that you lint your code with https://www.npmjs.com/package/standard .

Would you accept a PR that uses ESLint instead? That would mean we could drop 1 depDep.

**Comment by jokeyrhyme** [comment]
Just rebased this on master, and made the commit match the scope of the changes here

**Comment by scic** [comment]
feross/standard is since 6.0.5 compatible with eslint 2.0.0:
https://github.com/feross/standard/blob/master/CHANGELOG.md#605---2016-02-12

So there is no need to wait for v7.

**Pull request merged**
