### PR TITLE
Upgrade standard and config-standard

### PR DESCRIPTION
**Pull request by rasmusbe**

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
LGTM

**Comment by jokeyrhyme** [comment]
@Flet: think we can merge and `npm publish` this?

**Comment by Flet** [comment]
yeah for sure!

**Comment by Flet** [comment]
Published!

```
🕜 ❯ npm publish
+ eslint-config-semistandard@8.0.0
```

**Comment by Flet** [comment]
bumped `semistandard` as well:

```
🕝 ❯ npm publish
+ semistandard@10.0.0
```

**Comment by jokeyrhyme** [comment]
Yay, @flet, :clap: :D

**Pull request merged**
